ktor:
  application:
    modules:
      - com.eventos.ApplicationKt.module
  deployment:
    port: 8080

  database:
    url: "jdbc:postgresql://localhost:5432/eventos"
    user: "postgres"
    password: "4321"
    driver: "org.postgresql.Driver"
