ktor:
  deployment:
    port: ${DEPLOYMENT_PORT}

  application:
    modules:
      - com.eventos.ApplicationKt.module

database:
  url: ${DATASOURCE_URL}
  user: ${DATASOURCE_USERNAME}
  password: ${DATASOURCE_PASSWORD}
  driver: ${DATASOURCE_DRIVER}
